import * as fs from 'fs';
import * as path from 'path';

export class BridgeAgentManager {
  constructor(private agentsDir: string, private demosDir: string) {}

  /**
   * Installs a demo agent by copying it from the demos directory to the local agents directory.
   */
  async installDemoAgent(demoId: string): Promise<string> {
    const sourcePath = path.join(this.demosDir, `${demoId}.agent.md`);
    const destPath = path.join(this.agentsDir, `${demoId}.agent.md`);

    if (!fs.existsSync(sourcePath)) {
      throw new Error(`Demo agent '${demoId}' not found in demos directory.`);
    }

    if (fs.existsSync(destPath)) {
      throw new Error(`Agent '${demoId}' already exists in ${this.agentsDir}.`);
    }

    fs.copyFileSync(sourcePath, destPath);
    return `Demo agent '${demoId}' successfully installed to ${destPath}.`;
  }

  /**
   * Lists available demo agents.
   */
  listDemos(): string[] {
    if (!fs.existsSync(this.demosDir)) return [];
    return fs.readdirSync(this.demosDir)
      .filter(f => f.endsWith('.agent.md'))
      .map(f => path.basename(f, '.agent.md'));
  }

  /**
   * Simple deterministic creation helper.
   * This just writes the file. The "Wizard" part (asking questions)
   * is handled by the Bridge's state management.
   */
  async createAgent(id: string, config: any): Promise<string> {
    const filePath = path.join(this.agentsDir, `${id}.agent.md`);
    
    if (fs.existsSync(filePath)) {
      throw new Error(`Agent '${id}' already exists.`);
    }

    // basic YAML-like construction for the frontmatter
    const frontmatter = `---
type: ${config.type}
role: ${config.role}
capabilities: [ ${config.capabilities.join(', ')} ]
llm_provider: ${config.llm_provider || 'none'}
llm_model: ${config.llm_model || 'none'}
---

# ${config.role} Agent

Generated by pi-agent-bus wizard.
`;
    fs.writeFileSync(filePath, frontmatter);
    return `Agent '${id}' successfully created.`;
  }
}
